# Generated by Django 4.2.3 on 2023-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=80)),
                ('detail', models.TextField(blank=True, null=True)),
                ('telephone', models.IntegerField(unique=True)),
                ('naissance', models.DateField()),
            ],
        ),
    ]
