# Generated by Django 4.2.3 on 2023-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itanguriro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingendo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kuva', models.CharField(max_length=50)),
                ('gushika', models.CharField(max_length=50)),
                ('ibeyi', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ingenzi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
