# Generated by Django 4.2.3 on 2023-07-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itanguriro', '0002_ingendo_ingenzi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ingendo',
        ),
        migrations.DeleteModel(
            name='ingenzi',
        ),
    ]
