# Generated by Django 4.2.3 on 2023-07-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingenzi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('izina', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Ingenzi',
            },
        ),
        migrations.CreateModel(
            name='Urugendo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kuva', models.CharField(max_length=16)),
                ('gushika', models.CharField(max_length=16)),
                ('ibeyi', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Ingendo',
            },
        ),
        migrations.CreateModel(
            name='Itike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ingenzi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='urugendo.ingenzi')),
                ('urugendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urugendo.urugendo')),
            ],
            options={
                'verbose_name_plural': 'Amatike',
            },
        ),
    ]
