# Generated by Django 4.2.3 on 2023-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akabazo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='quantite',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
