# Generated by Django 4.2.3 on 2023-07-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minerval',
            old_name='nom',
            new_name='nom_eleve',
        ),
    ]
