# Generated by Django 4.2.3 on 2023-07-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0002_rename_nom_minerval_nom_eleve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='nom',
            new_name='nom_eleve',
        ),
        migrations.RenameField(
            model_name='minerval',
            old_name='nom_eleve',
            new_name='nom',
        ),
    ]
