# Generated by Django 4.2.3 on 2023-07-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0003_rename_nom_eleve_nom_eleve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='nom_eleve',
            new_name='nom',
        ),
    ]
