# Generated by Django 4.2.3 on 2023-07-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0005_minerval_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minerval',
            old_name='user',
            new_name='utilisateur',
        ),
    ]
