# Generated by Django 4.2.3 on 2023-08-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0008_classe_argent_alter_minerval_minerval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minerval',
            name='minerval',
            field=models.IntegerField(unique=True),
        ),
    ]
