# Generated by Django 4.2.3 on 2023-08-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0009_alter_minerval_minerval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='argent',
        ),
    ]
