# Generated by Django 4.2.3 on 2023-08-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0010_remove_classe_argent'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minerval',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
