# Generated by Django 4.2.3 on 2023-08-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishure', '0011_classe_date_eleve_date_minerval_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='date',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='date',
        ),
        migrations.RemoveField(
            model_name='minerval',
            name='date',
        ),
    ]
